### ISSUE TITLE
add dtn7-kotlin in the list of implementation

### ISSUE THREAD

**Issue by Marlinski** [dtn7/dtn7.github.io#1]
Hi,

I have just finished an implementation of dtn7 in kotlin:

https://github.com/NodleCode/dtn7-kotlin/

it is simple but quite extensible. Its compatibility has been successfully tested with dtn7-go.
can you also add me as member of the repo?

Regards

**Comment by Marlinski** [comment]
@oxzi ^

**Comment by oxzi** [comment]
I said it before, I am very happy to see another implementation of the latest Bundle Protocol. By adopting our naming scheme, I feel honored. Gladly I updated the web page and listed your implementation together with a short post.

Thanks for highlighting me. I am not sure why neither I nor anybody else was watching this repository.

Some historical background. Originally I started dtn7-go, then just called dtn7, as part of my bachelor's thesis at our [distributed systems research group](https://www.uni-marburg.de/en/fb12/research-groups/distsys). A member of this group, @gh0st42, started another dtn7 implementation in Rust. Thus, we changed the naming scheme to dtn7-go and dtn7-rs. However, he then switched to the TU Darmstadt where he continued to develop dtn7-rs. Thus, these two implementations have a same origin.
Especially with this background, I am very happy to welcome another DTN7 implementation.

Thus, however, this website was also initially intended as a project page or to list the publications. I will talk with the others about this website and see if and how we can reorganize it.

**Comment by Marlinski** [comment]
thanks for adding me

Outside of the IETF, there doesn't seem to be much effort to list actual implementation of the protocol and discuss engineering decisions, I think it is also because there are so few implementations. I actually did one some years ago ([Terra](https://github.com/Marlinski/Terra)) but in retrospect I think the implementation was not very good (I do not even maintain it anymore) :-) 

I find your implementation very good and that motivated me to do another one in Kotlin (instead of Java). I think it would be nice if this webpage dtn7.github.io becomes the reference for current and future implementation, I believe there are a few others like upcn https://upcn.eu/ maybe we should contact them to join the group if it isn't the case already.

we need more dtn node running and interacting with each others !

**Comment by oxzi** [comment]
@Marlinski: In the meantime we created a [DTN Awesome List](https://github.com/dtn7/awesome-dtn). Please feel free to propose additional software. Likewise, you are welcome to PR changes to this repository.
